import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#3D4544',
        justifyContent: 'space-around',
    },
    backgroundImage: {
        flex: 1,
        justifyContent: "center"
    },
    body: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
    },
    headerIcon: {
        height: 45,
        width: 45,
        resizeMode: 'contain',
        marginRight: 10,
    },
    headerText: {
        color: 'white',
        fontSize: 15,
        fontFamily: 'Oswald_500Medium',
        textAlign: 'center',
        alignContent: 'center',
    },
    inputContainer: {
        width: '100%', 
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,             
    },
    submitContainer: {
        marginTop: 20,
        marginBottom: 20,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    buttonLayout: {
        backgroundColor: '#A4C3B2',
        marginTop: 10,
        marginBottom: 10,
        width: "70%",
        height: 60,
        padding: 15,
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
    }, 
    sliderButtonLayout: {
        backgroundColor: ' rgba(220, 220, 225, 0.5);',
        marginTop: 10,
        marginBottom: 10,
        width: "90%",
        height: 55,
        padding: 15,
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
    }, 
    pickerButtonLayout: {
        backgroundColor: ' rgba(220, 220, 225, 0.5);',
        marginTop: 10,
        marginBottom: 10,
        width: "90%",
        height: 55,
        padding: 15,
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
    }, 
    submitButtonLayout: {
        backgroundColor: '#A4C3B2',
        marginTop: 5,
        margin: 5,
        width: "80%",
        height: 55,
        padding: 15,
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
    }, 
    buttonCheckBoxLayout: {
        backgroundColor: ' rgba(220, 220, 225, 0.5);',
        marginTop: 5,
        margin: 5,
        width: "90%",
        height: 60,
        padding: 15,
        borderRadius: 5,
        justifyContent: 'center',
        alignItems: 'center',
    }, 
    buttonText: {
        color: '#545454',
        fontSize: 16,
        fontFamily: 'Oswald_500Medium',
    },
    inputText: {
        color: 'black',
        fontFamily: 'Oswald_300Light',
        fontSize: 16,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center'
    },
    inputCheckBoxTitleText: {
        color: 'black',
        fontFamily: 'Oswald_300Light',
        fontSize: 18,
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center'
    },
    inputTextCheckBox: {
        color: 'black',
        fontFamily: 'Oswald_300Light',
        fontSize: 16,
        width: '100%',
        textAlign: 'center',
    },
    inputFieldRowContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
    },
    inputFieldCheckBoxRowContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        alignSelf: 'center',
    },
    inputFieldRadio: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: ' rgba(220, 220, 225, 0.5);',
        width: '90%',
        padding: 10,
        margin: 5,
        borderRadius: 10,
    },
    defaultPicker: {
        width: "90%",
        height: 50,
        borderWidth: 1,
        borderRadius: 5,
        borderColor: "#DDDDDD",
        marginBottom: 20,
        paddingLeft: 15,
    },
    checkbox: {
        margin: 4,
        alignSelf: "center",
        justifyContent: 'center',
        alignItems: 'center',
        padding: 15,

    },
    inputField: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: ' rgba(220, 220, 225, 0.5);',
        borderBottomColor: '#F7AD3B',
        borderBottomWidth: 0,
        paddingHorizontal: 15,
        paddingVertical: 10,
        marginTop: 20,
        borderRadius: 10,
        width: '90%',
    },
    
});
