export enum Screens{
    LOGIN='Login',
    HOME='Home',
    ADD_PRODUCTS='Agregar producto',
    ADD_ADMINS='Agregar admin/supervisor',
    ADD_TABLE='Agregar mesa',
    QRCode='Codigo QR',
    ADD_CLIENT='Agregar cliente',
    ADD_EMPLOYEE='Agregar empleado',
    CLIENT_LIST='Lista de clientes',
    QR_BUTTON='Escanear QR',
    QR_SCANNER="QRScannerScreen",
    CHAT='Hablá con nosotros',
    CLIENT_HOME="Principal Clientes",
    WAITING_CLIENT_LIST="Lista de espera",
    ADD_POLL = "Agregar encuesta",
    GRAPHIC_SCREEN="Graficos",
    GUESS_THE_NUMBER="Adivina el numero",
}